#!/usr/bin/env python3
from pathlib import Path

COMP = Path(__file__).resolve().parents[1] / "components"
o = "<" + chr(100) + "iv"
c = "</" + chr(100) + "iv>"


def save(name: str, lines: list[str]) -> None:
    COMP.joinpath(name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", name)


save(
    "Hero.jsx",
    [
        'import Button from "./ui/Button";',
        'import Container from "./ui/Container";',
        'import HeroChat from "./HeroChat";',
        "",
        'const trustLogos = ["Logoipsum", "★ Vertex", "Northstar", "◆ Lumen", "Atlas Co.", "Helios"];',
        "",
        "export default function Hero() {",
        "  return (",
        '    <section className="hero">',
        f'      {o} className="hero__gradient" aria-hidden="true" />',
        '      <Container className="hero__inner">',
        f'        {o} className="hero__copy">',
        '          <span className="badge">',
        '            <span className="badge__icon" aria-hidden="true">✦</span>',
        "            AI shopping assistant for WooCommerce",
        "          </span>",
        '          <h1 className="display">',
        "            Turn your WooCommerce store into a",
        '            <span className="text-indigo"> conversational</span> shopping experience',
        "          </h1>",
        '          <p className="hero__sub">',
        "            Give shoppers instant answers, personalized product recommendations, and guided buying",
        "            help with an AI assistant trained on your WooCommerce products, categories, pages, and",
        "            store policies.",
        f"          </p>",
        f'          {o} className="hero__actions">',
        '            <Button href="#cta">Start Free Trial</Button>',
        '            <Button href="#how" variant="ghost">See How It Works</Button>',
        f"          {c}",
        '          <p className="hero__trust">',
        '            <span className="dot-green" aria-hidden="true" />',
        "            No credit card required · Works with WooCommerce · Install in minutes",
        f"          </p>",
        f"        {c}",
        f'        {o} className="hero__visual">',
        "          <HeroChat />",
        f'          {o} className="float-card float-card--1" aria-hidden="true">',
        '            <div className="float-card__icon" style={{ background: "#D4FC57" }}>',
        '              <svg viewBox="0 0 24 24" width="16" height="16" fill="none">',
        '                <path d="M12 2v20M2 12h20" stroke="#0A0A0A" strokeWidth="2.5" strokeLinecap="round" />',
        "              </svg>",
        f"            {c}",
        f"            {o}>",
        '              <div className="float-card__label">Conversion lift</div>',
        '              <div className="float-card__value">+27.4%</div>',
        f"            {c}",
        f"          {c}",
        f'          {o} className="float-card float-card--2" aria-hidden="true">',
        '            <div className="float-card__icon" style={{ background: "#E0E7FF" }}>',
        '              <svg viewBox="0 0 24 24" width="14" height="14" fill="none">',
        '                <path d="M20 12a8 8 0 11-16 0 8 8 0 0116 0z" stroke="#3F4FE5" strokeWidth="2" />',
        '                <path d="M9 12l2 2 4-4" stroke="#3F4FE5" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />',
        "              </svg>",
        f"            {c}",
        f"            {o}>",
        '              <div className="float-card__label">Questions answered</div>',
        '              <div className="float-card__value">12,840</div>',
        f"            {c}",
        f"          {c}",
        f"        {c}",
        "      </Container>",
        "      <Container>",
        f'        {o} className="trust">',
        '          <div className="trust__label">Trusted by ambitious WooCommerce stores —</div>',
        '          <div className="trust__logos" aria-hidden="true">',
        "            {trustLogos.map((logo) => (",
        '              <span key={logo} className="logo-text">{logo}</span>',
        "            ))}",
        f"          {c}",
        f"        {c}",
        "      </Container>",
        "    </section>",
        "  );",
        "}",
    ],
)